steps:
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/sit323-23t1-pei-365a95e/gcr.io/inn997109/webapp :latest', '.']

 

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'docker'
  args:
    - 'run'
    - '--rm'
    - 'gcr.io/sit323-23t1-pei-365a95e/jinwei-test-image:latest'
    - 'npm'
    - 'test'
