name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image
        # Add steps to build and push Docker image

      - name: Deploy to Kubernetes
        # Add steps to deploy to Kubernetes cluster

