name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: inn997109/sit323week5:latest
        # Add steps to build and push Docker image

      - name: Deploy to Docker
        run: |
          docker run -d -p 8080:8080 inn997109/sit323week5:latest
        # Add any additional deployment steps or configurations


